//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiProgramm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string CarNumber { get; set; }
        public string WorkerPhone { get; set; }
        public string Model { get; set; }
        public string Class { get; set; }
        public bool СhildSeat { get; set; }
    
        public virtual TaxiDriver TaxiDriver { get; set; }
    }
}
